In [2]:
import numpy as np
import numpy.linalg as lin

import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

import pandas as pd

In [4]:
dataframe = pd.read_csv("movieratings.csv")
dataframe.head(n=100)

,Name,Once upon a time in Hollywood (2019),Dark Knight (2008),Farenheit 9/11 (2004),Gladiator (2000),No country for old men (2007),Ocean's 8,Call me by your name (2018),Singin' in the Rain (1952),Groundhog Day (1993),...,Parks and Recreation (TV),Friends (TV),Veronica Mars (TV),"Battlestar Galactica (TV, 2004)",Brokeback Mountain (2005),Sense8 (TV),Bohemian Rhapsody (2019),Godfather,Ghost in the shell,Attack on Titan
0,F2,3,3,5,3,1,3,3,4,3,...,4,5,1,3,4,3,4.0,3,3,5.0
1,S3,1,1,5,1,1,3,3,2,5,...,3,4,1,1,1,1,5.0,3,1,1.0
2,D4,3,4,3,4,2,4,3,2,5,...,5,4,3,3,4,4,2.0,3,3,4.0
3,K5,3,4,3,4,3,3,3,2,2,...,3,3,2,5,3,3,3.0,2,2,2.0
4,C6,4,5,3,3,3,4,3,3,3,...,2,3,2,2,3,2,2.0,4,4,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,A58,2,5,1,2,3,2,3,3,3,...,2,4,1,2,2,3,4.0,3,4,5.0
57,G59,4,5,1,3,2,1,1,2,3,...,2,2,1,4,2,4,3.0,5,2,4.0
58,B60,4,5,5,5,2,3,2,3,4,...,2,5,4,4,4,4,4.0,5,5,5.0
59,M61,3,4,2,4,2,3,1,3,4,...,2,3,1,4,3,4,5.0,4,4,NaN
60,J62,3,2,3,2,3,3,2,3,4,...,3,2,2,3,3,3,4.0,2,4,3.0

In [5]:
# we skip the first rwo (empty, full of nans) and the first col (names).
ratings = dataframe.to_numpy()[1:-1,1:-1].astype(np.float32)

# there may be stray examples not rated, get rid of them by replacing nan by 3, the "meh" rating
x = np.isnan(ratings)
ratings[x]=3
means = np.mean(ratings, axis=0)
X = ratings - means

u,s,vt = lin.svd(X)

In [6]:
print(X.shape, u.shape, s.shape, vt.shape)

print(np.round(u[:,:26] @ np.diag(s[:26]) @vt[:26,:] +means,2))

(59, 26) (59, 59) (26,) (26, 26)
[[1. 1. 5. ... 5. 3. 1.]
 [3. 4. 3. ... 2. 3. 3.]
 [3. 4. 3. ... 3. 2. 2.]
 ...
 [4. 5. 1. ... 3. 5. 2.]
 [4. 5. 5. ... 4. 5. 5.]
 [3. 4. 2. ... 5. 4. 4.]]

In [7]:
print(ratings.shape)
print(np.round(s,2))

(59, 26)
[18.85 12.87 11.89 10.81 10.24  9.14  8.91  8.62  8.01  7.46  7.27  6.67
  6.36  6.17  5.85  5.59  5.27  4.84  4.77  4.38  3.97  3.63  3.41  3.26
  2.79  2.47]

In [8]:
print(np.round(s,3))
print(s.shape)

sapprox = s
sapprox[5:] =0
print(np.round(sapprox,2))

[18.85  12.871 11.89  10.81  10.241  9.14   8.906  8.619  8.01   7.459
  7.267  6.672  6.36   6.17   5.848  5.593  5.268  4.835  4.769  4.382
  3.969  3.632  3.413  3.256  2.79   2.469]
(26,)
[18.85 12.87 11.89 10.81 10.24  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.  ]

In [9]:
v = vt.T
print(v.shape)

(26, 26)

In [9]:
print(np.round(v @ v.T,1))

[[ 1. -0.  0.  0. -0. -0. -0. -0.  0.  0.  0. -0.  0. -0. -0. -0. -0. -0.
  -0. -0.  0. -0. -0.  0.  0.  0.]
 [-0.  1.  0. -0. -0.  0. -0. -0. -0.  0.  0.  0. -0. -0.  0. -0. -0. -0.
   0.  0.  0. -0. -0. -0. -0.  0.]
 [ 0.  0.  1. -0. -0.  0. -0.  0.  0. -0. -0. -0. -0. -0. -0.  0.  0. -0.
   0. -0.  0. -0. -0.  0.  0. -0.]
 [ 0. -0. -0.  1. -0. -0. -0.  0. -0.  0. -0. -0.  0. -0. -0. -0.  0.  0.
   0. -0. -0.  0.  0.  0.  0.  0.]
 [-0. -0. -0. -0.  1. -0.  0.  0. -0. -0. -0.  0. -0.  0.  0.  0. -0.  0.
   0. -0. -0.  0.  0.  0. -0. -0.]
 [-0.  0.  0. -0. -0.  1.  0. -0. -0. -0. -0. -0. -0.  0.  0. -0.  0.  0.
  -0. -0. -0. -0.  0.  0.  0. -0.]
 [-0. -0. -0. -0.  0.  0.  1.  0.  0. -0.  0.  0.  0. -0.  0.  0.  0. -0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0. -0.  0.  1. -0. -0.  0. -0.  0. -0.  0. -0. -0. -0.
  -0. -0.  0. -0.  0. -0. -0.  0.]
 [ 0. -0.  0. -0. -0. -0.  0. -0.  1. -0. -0. -0.  0. -0.  0.  0.  0.  0.
   0. -0.  0. -0. -0.  0.  0.  0.]
 [ 0.  0. -0.  0. -0. -0. -0. -0. -0.  1.  0. -0.  0. -0.  0.  0.  0.  0.
  -0.  0.  0. -0. -0. -0.  0.  0.]
 [ 0.  0. -0. -0. -0. -0.  0.  0. -0.  0.  1. -0. -0. -0. -0. -0.  0.  0.
   0.  0. -0. -0.  0. -0. -0. -0.]
 [-0.  0. -0. -0.  0. -0.  0. -0. -0. -0. -0.  1.  0. -0.  0. -0.  0. -0.
  -0. -0.  0. -0. -0.  0.  0.  0.]
 [ 0. -0. -0.  0. -0. -0.  0.  0.  0.  0. -0.  0.  1. -0.  0. -0. -0. -0.
   0. -0. -0.  0. -0. -0. -0.  0.]
 [-0. -0. -0. -0.  0.  0. -0. -0. -0. -0. -0. -0. -0.  1. -0. -0. -0. -0.
   0. -0.  0. -0.  0.  0. -0.  0.]
 [-0.  0. -0. -0.  0.  0.  0.  0.  0.  0. -0.  0.  0. -0.  1.  0.  0.  0.
  -0.  0.  0. -0.  0.  0. -0. -0.]
 [-0. -0.  0. -0.  0. -0.  0. -0.  0.  0. -0. -0. -0. -0.  0.  1.  0. -0.
   0.  0. -0. -0. -0. -0.  0. -0.]
 [-0. -0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0. -0. -0.  0.  0.  1. -0.
  -0.  0.  0. -0.  0.  0. -0. -0.]
 [-0. -0. -0.  0.  0.  0. -0. -0.  0.  0.  0. -0. -0. -0.  0. -0. -0.  1.
   0. -0. -0.  0.  0. -0. -0.  0.]
 [-0.  0.  0.  0.  0. -0.  0. -0.  0. -0.  0. -0.  0.  0. -0.  0. -0.  0.
   1.  0.  0. -0.  0. -0.  0.  0.]
 [-0.  0. -0. -0. -0. -0.  0. -0. -0.  0.  0. -0. -0. -0.  0.  0.  0. -0.
   0.  1.  0. -0.  0.  0.  0. -0.]
 [ 0.  0.  0. -0. -0. -0.  0.  0.  0.  0. -0.  0. -0.  0.  0. -0.  0. -0.
   0.  0.  1.  0. -0.  0. -0.  0.]
 [-0. -0. -0.  0.  0. -0.  0. -0. -0. -0. -0. -0.  0. -0. -0. -0. -0.  0.
  -0. -0.  0.  1. -0. -0. -0. -0.]
 [-0. -0. -0.  0.  0.  0.  0.  0. -0. -0.  0. -0. -0.  0.  0. -0.  0.  0.
   0.  0. -0. -0.  1. -0. -0.  0.]
 [ 0. -0.  0.  0.  0.  0.  0. -0.  0. -0. -0.  0. -0.  0.  0. -0.  0. -0.
  -0.  0.  0. -0. -0.  1. -0. -0.]
 [ 0. -0.  0.  0. -0.  0.  0. -0.  0.  0. -0.  0. -0. -0. -0.  0. -0. -0.
   0.  0. -0. -0. -0. -0.  1. -0.]
 [ 0.  0. -0.  0. -0. -0.  0.  0.  0.  0. -0.  0.  0.  0. -0. -0. -0.  0.
   0. -0.  0. -0.  0. -0. -0.  1.]]

In [32]:
usigma = u[:,:26] @ np.diag(sapprox)

print(usigma.shape)
Xapprox = usigma @ vt

meanratings = np.mean(ratings, axis=0)
predratings = Xapprox + meanratings
print('Approximate: ',predratings[:5,:5])
print('True: ',ratings[:5,:5])

(59, 26)
Approximate:  [[0.88718534 1.101284   2.8596613  1.4945695  0.35503674]
 [2.7006295  3.620013   3.2670913  3.412057   2.3522089 ]
 [2.8339202  3.9221613  3.0754366  3.6236403  3.101586  ]
 [3.1373506  4.505858   2.949022   4.10042    3.5543702 ]
 [2.301337   3.4716864  3.2791522  3.2286947  3.1189191 ]]
True:  [[1. 1. 5. 1. 1.]
 [3. 4. 3. 4. 2.]
 [3. 4. 3. 4. 3.]
 [4. 5. 3. 3. 3.]
 [1. 4. 3. 3. 4.]]

In [41]:
# top eigenvector of X^TX=== first column of v 
# "Most typical user"
ind = 1
#print(v[:,ind])

attachedv = zip(v[:,ind], dataframe.columns[1:])
movies = []
for elt in iter(attachedv):
    if np.abs(elt[0]) > .2:
        print(elt)
        movies.append(elt[1])
        
print()

(-0.37406564, 'Dark Knight (2008)')
(-0.31349522, 'No country for old men (2007)')
(0.47848177, "Ocean's 8")
(0.24769787, 'Planet Earth (documentary)')
(0.23609659, 'Friends (TV)')
(-0.28989413, 'Battlestar Galactica (TV, 2004)')
(0.26575094, 'Bohemian Rhapsody (2019)')
(-0.30667964, 'Ghost in the shell')

In [42]:
# uses ind from previous cell
#print(u[:,ind])
selectedmovies = dataframe[movies]
attachedu = zip(u[:,ind], dataframe['Name'])

num= 0
for elt in iter(attachedu):
    if np.abs(elt[0]) > .2:
        print(elt,'\n', selectedmovies.iloc[num], '\n ---------------')
    num +=1

(0.29549047, 'F2')
 Dark Knight (2008)                 3.0
No country for old men (2007)      1.0
Ocean's 8                          3.0
Planet Earth (documentary)         3.0
Friends (TV)                       5.0
Battlestar Galactica (TV, 2004)    3.0
Bohemian Rhapsody (2019)           4.0
Ghost in the shell                 3.0
Name: 0, dtype: float64
 ---------------
(-0.22748804, 'K7')
 Dark Knight (2008)                 4.0
No country for old men (2007)      4.0
Ocean's 8                          3.0
Planet Earth (documentary)         5.0
Friends (TV)                       3.0
Battlestar Galactica (TV, 2004)    3.0
Bohemian Rhapsody (2019)           5.0
Ghost in the shell                 3.0
Name: 5, dtype: float64
 ---------------
(0.2385178, 'R12')
 Dark Knight (2008)                 4.0
No country for old men (2007)      2.0
Ocean's 8                          3.0
Planet Earth (documentary)         3.0
Friends (TV)                       4.0
Battlestar Galactica (TV, 2004)    3.0
Bohemian Rhapsody (2019)           3.0
Ghost in the shell                 3.0
Name: 10, dtype: float64
 ---------------
(0.2217204, 'E41')
 Dark Knight (2008)                 4.0
No country for old men (2007)      3.0
Ocean's 8                          5.0
Planet Earth (documentary)         5.0
Friends (TV)                       1.0
Battlestar Galactica (TV, 2004)    2.0
Bohemian Rhapsody (2019)           4.0
Ghost in the shell                 4.0
Name: 39, dtype: float64
 ---------------
(-0.2834699, 'K44')
 Dark Knight (2008)                 4.0
No country for old men (2007)      2.0
Ocean's 8                          4.0
Planet Earth (documentary)         4.0
Friends (TV)                       5.0
Battlestar Galactica (TV, 2004)    1.0
Bohemian Rhapsody (2019)           2.0
Ghost in the shell                 2.0
Name: 42, dtype: float64
 ---------------
(-0.20115133, 'J47')
 Dark Knight (2008)                 5.0
No country for old men (2007)      2.0
Ocean's 8                          5.0
Planet Earth (documentary)         5.0
Friends (TV)                       4.0
Battlestar Galactica (TV, 2004)    5.0
Bohemian Rhapsody (2019)           5.0
Ghost in the shell                 5.0
Name: 45, dtype: float64
 ---------------
(0.33471763, 'I48')
 Dark Knight (2008)                 5.0
No country for old men (2007)      4.0
Ocean's 8                          2.0
Planet Earth (documentary)         1.0
Friends (TV)                       3.0
Battlestar Galactica (TV, 2004)    3.0
Bohemian Rhapsody (2019)           3.0
Ghost in the shell                 3.0
Name: 46, dtype: float64
 ---------------
(-0.2017926, 'A56')
 Dark Knight (2008)                 4.0
No country for old men (2007)      5.0
Ocean's 8                          3.0
Planet Earth (documentary)         2.0
Friends (TV)                       3.0
Battlestar Galactica (TV, 2004)    3.0
Bohemian Rhapsody (2019)           2.0
Ghost in the shell                 5.0
Name: 54, dtype: float64
 ---------------

In [ ]:
# Top eigenvector is a linear combination of all of you. The coefficients of the linear combination are in w1. 
# As an approximate gauge of the contribution, we look at the unit vector along w1 (ie, the first column of 
# the matrix u)

u1= u[:,0]

In [ ]:
print(np.round(u1*u1,3))

In [ ]:
u2 = u[:,1]
print(np.round(u2*u2,3))

In [ ]:
# top eigenvector of XX^T=== first column of u 
# "Most typical genre"

u1 = u[:,0]
print(u[:,0])

# Recall u_1 = X v_1/sqrt(lambda_1) where v_1 was the unit eigenvector of X^TX with eigenvalue lambda_1
# u_1 is the first col of the matrix u, the eigenvector of length 1 of XX^T with eigenvalue lambda_1

print(np.round(u1-X @ (v1 / s[0]),3))

In [ ]:
movies=(dataframe.columns[1:-1])

In [ ]:
# Let us examine the contribution of each movie to the eigenvector u_i. Because
# u_i = X v_i /\sqrt{lambda}, u_i is a linear combination of the cols of X, and
# that the components of the vector v_i can be interpreted as
# the coefficients of the movies contributing to the eigenvector u_i.
# Since length of v_i is 1, we will interpret the square of each component of
# v_i as the strength of contribution of the corresponding movie to u_i

# Change the number in the line below to access different eigenvectors.
v2= v[:,4]

p = len(dataframe.columns[1:-1])

# the following line sorts the squared coefficients of v2
ind = sorted(range(p), key = lambda k: (v2*v2)[k])

# and prints the movies with the 5 highest contributions to the eigenvector u
# the last movie in the list has the highest contribution.
print(movies[ind[-10:]])
print(np.sum((v2*v2)[ind[-10:]]))
print(v2[ind[-10:]])

In [ ]:
print(ind)

In [ ]:
print(ratings[:,23])